# Quantum Max Cut / Heisenberg antiferromagnet on a 6-vertex bipartite graph
# via the swap-operator ncSoS hierarchy of Watts, Chowdhury, Epperly, Helton, Klep
# (arXiv:2307.15661), solved with PCPOP.jl and compared with exact diagonalization.
#
# For qubits i ≠ j the swap is  s_ij = (1 + X_iX_j + Y_iY_j + Z_iZ_j)/2  and
#   σ_i·σ_j = 2 s_ij - 1,      QMC edge term  (1 - σ_i·σ_j)/4 = (1 - s_ij)/2 .
# The algebra generated by qubit swaps is presented by
#   (R1) s_ij^2 = 1                                  (dichotomic / unipotent)
#   (R2) s_ij s_kl = s_kl s_ij      {i,j} ∩ {k,l} = ∅  (partial commutation)
#   (R3) s_ij s_jk = s_ik s_ij                        (braid / conjugation)
#   (R4) s_ij s_jk + s_jk s_ij = s_ij + s_jk + s_ik - 1   (qubit "triangle" identity)
# R1 and R2 are quotiented out in the monoid; R3 and R4 enter as op_eq (localizing matrices).

using PCPOP, JuMP, LinearAlgebra, Combinatorics

############################
##  1. Graph              ##
############################

n = 6
A, B = [1, 2, 3], [4, 5, 6]                  # bipartition
graph = :C6                                 # :K33 or :C6 (both bipartite)
if graph == :K33
    edges = [(i, j, 1.0) for i in A for j in B]
elseif graph == :C6
    edges = [(min(i, j), max(i, j), 1.0) for (i, j) in zip(1:n, [2:n; 1])]
end

############################
##  2. Variables          ##
############################

pairs = collect(combinations(1:n, 2))        # all 15 transpositions (i < j)
@pcmonoid M s[length(pairs), 0]
idx = Dict(Tuple(p) => k for (k, p) in enumerate(pairs))
sw(i, j) = s[idx[(min(i, j), max(i, j))]]    # s_ij = s_ji

############################
##  3. Commutations (R2)  ##
############################

for (p, q) in combinations(pairs, 2)
    isdisjoint(p, q) && @comms s[idx[Tuple(p)]] s[idx[Tuple(q)]]
end

############################
##  4. Dichotomic (R1)    ##
############################

Unipotent.(s)

############################
##  5. Build monoid       ##
############################

build(M)

############################
##  6. op_eq (R3, R4)     ##
############################

op_eq = []
for (i, j, k) in permutations(1:n, 3)
    # braid relation; PCPOP's localizing block imposes L(x' g y) = 0 only for x ≤ y
    # in the basis order, so the adjoint is added to cover the other triangle
    g = sw(i, j)*sw(j, k) - sw(i, k)*sw(i, j)
    push!(op_eq, g, conj(g))
end
for (i, j, k) in combinations(1:n, 3), (a, b, c) in [(i, j, k), (j, k, i), (k, i, j)]
    # triangle identity with each pair of the triangle as the anticommutator
    push!(op_eq, sw(a, b)*sw(b, c) + sw(b, c)*sw(a, b) - sw(a, b) - sw(b, c) - sw(a, c) + 1)
end

############################
##  7. Objective          ##
############################

# Heisenberg Hamiltonian H = Σ_ij w_ij σ_i·σ_j = Σ_ij w_ij (2 s_ij - 1)
H = sum(w*(2*sw(i, j) - 1) for (i, j, w) in edges)

############################
##  8. Optimize           ##
############################

# pcpop(·, k) uses degree-k localizing blocks and a degree-(k+1) moment matrix, so k = 1
# is level 2 of the paper's hierarchy (moments of degree ≤ 4).
k = 1
@time sdp_val, model, _ = pcpop(H, k; min = true, op_eq = op_eq)
println("Termination status  ", termination_status(model))

############################
##  9. Exact diag.        ##
############################

const X = [0 1; 1 0]
const Y = [0 -im; im 0]
const Z = [1 0; 0 -1]
site(P, i) = kron([m == i ? P : Matrix(I, 2, 2) for m in 1:n]...)
swapmat(i, j) = real((I + site(X, i)*site(X, j) + site(Y, i)*site(Y, j) + site(Z, i)*site(Z, j))/2)

S = Dict((i, j) => swapmat(i, j) for i in 1:n, j in 1:n if i != j)
@assert all(S[(i, j)]*S[(j, k)] ≈ S[(i, k)]*S[(i, j)] for (i, j, k) in permutations(1:n, 3))
@assert all(
    S[(i, j)]*S[(j, k)] + S[(j, k)]*S[(i, j)] ≈ S[(i, j)] + S[(j, k)] + S[(i, k)] - I
    for (i, j, k) in permutations(1:n, 3)
)

Hmat = Symmetric(sum(w*(2*S[(i, j)] - I) for (i, j, w) in edges))
ed_val = eigmin(Hmat)

############################
## 10. Comparison         ##
############################

W = sum(w for (_, _, w) in edges)
println("Graph               ", graph, "  with ", length(edges), " edges")
println("SDP lower bound λ_min(H)  ", sdp_val)
println("ED            λ_min(H)    ", ed_val)
println("gap                       ", sdp_val - ed_val)
println("QMC value  SDP upper bound ", (W - sdp_val)/4, "   ED ", (W - ed_val)/4)
